### ISSUE TITLE
os108.org still says os108.github.io in the site heading

### ISSUE THREAD

**Issue by sahilister** [OS108/os108.org#2]
![os108](https://user-images.githubusercontent.com/52946452/98541088-c7eb9800-2286-11eb-8380-21a324b4c6cb.png)

os108.org still says os108.github.io in the site heading. 

Is the there any particular reason for still keeping it that way (despite the hyperlink beneath it pointing to os108.org)?

**Comment by jaypatelani** [comment]
Hi,
It is the way github pages template is adjusted. I haven't focused more on Website of project.

Thanks.

**Comment by sahilister** [comment]
Alright, thanks for answering.

(though I believe it can work with os108.org too in the header.)

**Comment by jaypatelani** [comment]
> Alright, thanks for answering.
> 
> (though I believe it can work with os108.org too in the header.)

Please do share pull request. :)
Thanks,
Jay

**Comment by sahilister** [comment]
The way to update with the present setup can't be done through a pull request. See if it's feasible enough to do the following. 


1. As seen [here](https://github.com/pages-themes/minimal/blob/25df166e45b4f6061b26a8793526573f4acc80d9/_layouts/default.html#L17) in minimal theme repository, site title is taken from GitHub repository name, simply editing this repository title from `os108.github.io` to `os108.org` would replace the title.
2. As `os108.org` is an apex domain and repository name is changed, the `ANAME` has to be updated in DNS records to point to the new GitHub Pages URL which can be seen under [GitHub Pages](https://docs.github.com/assets/images/help/pages/save-custom-domain.png) in Settings (a simple edit to previous record to replace name would do).

**Comment by jaypatelani** [comment]
Thanks and changes done :)

**Comment by sahilister** [comment]
Glad it helped.
